version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"
  jobs:
    pre_build:
      # Generate the Sphinx configuration for this Jupyter Book so it builds.
      - "jupyter-book config sphinx _documentation/"

python:
  install:
    - method: pip
    - requirements: requirements.txt
      path: .
      extra_requirements:
      - sphinx

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true
