version: 2

build:
  os: openSUSE Tumbleweed
  tools:
    python: "3.11"
  jobs:
    pre_build:
      # Generate the Sphinx configuration for this Jupyter Book so it builds.
      - "jupyter-book config sphinx _documentation/"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
      - sphinx

sphinx:
  builder: html
  fail_on_warning: true
